#!/usr/bin/python3
# -*- coding: UTF-8 -*-

###############################
# PYTHON COMO UMA CALCULADORA #
###############################

print()
print("-------------------------------")
print("* PYTHON COMO UMA CALCULADORA *")
print("-------------------------------")
print()
print("AS QUATROS OPERAÇÕES BÁSICA DA MATEMÁTICA:")
print("Usamos os símbolos: +, -, * e / para soma, subtração, multiplicação e divisão, veja: ")
print()
print("Adição:")
print("11 + 4 + 5 =", 11 + 4 + 5)
print()
print("Subtração:")
print("11 - 4 - 5 =", 11 - 4 - 5)
print()
print("Multiplicação:")
print("4 * 3 =", 4 * 3)
print()
print("Divisão:")
print("12 / 5 =", 12 / 5)
print()

print("Potenciação:")
print("Potenciação se usa **, para calcular 2³, ficará: 2 ** 3, veja só:")
print("2³ =", 2 ** 3)

print()
print("Divisão inteira e resto:")
print("Nesse tipo de operação, um número é dividido por outro e depois o resultado é ARREDONDADO para baixo.")
print("Se usa: // para efetuar a operação.")
print("3 // 2 =", 3 // 2)

print()
print("Cálculo do resto da divisão de um número por outro:")
print("17 % 5 =", 17 % 5)
print("----------------------------------------------")
print()

print("Abaixo, temos alguns exercícios de exemplo:")
print("1. Fany comprou uma TV WebOS no valor de R$ 2099,00, dividiu em 12 vezes sem juros.")
print("   Qual o valor de cada parcela?")
print("   Resposta:", 2099 / 12)
print()

print("2. Meire fez dez anos de idade em 6 de dezembro de 2020. Calcule quantidades de dias viveu nesse perído.")
print("   Meire nasceu em 6 de dezembro de 2010, logo, Meire viveu, nesse período:", 10 * 365, "dias.")
print("   Meire viveu nesse período:", 3650 * 24, "horas.")
print("   Meire viveu nesse período:", 87600 * 60, "minutos.")
print("   Meire viveu nesse período:", 5256000 * 60, "segundos.")
print("   Meire viveu nesse período:", 315360000 * 1000, "milésimos de segundos.")
print()

print('---------------------')
print("CÁLCULOS COM STRING's")
print('---------------------')
print("Obs.: Cálculos com strings apenas podem ser realizadas com a adição e/ou multiplicação.")
print()

linguagem = "PYTHON "
print("PYTHON x 1 = ", linguagem * 1)
print("PYTHON x 2 = ", linguagem * 2)
print("PYTHON x 3 = ", linguagem * 3)
print("PYTHON x 4 = ", linguagem * 4)
print("PYTHON x 5 = ", linguagem * 5)
print("PYTHON x 6 = ", linguagem * 6)
print("PYTHON x 7 = ", linguagem * 7)
print("PYTHON x 8 = ", linguagem * 8)
print("PYTHON x 9 = ", linguagem * 9)
print("PYTHON x 9 = ", linguagem * 9)
print("PYTHON x 8 = ", linguagem * 8)
print("PYTHON x 7 = ", linguagem * 7)
print("PYTHON x 6 = ", linguagem * 6)
print("PYTHON x 5 = ", linguagem * 5)
print("PYTHON x 4 = ", linguagem * 4)
print("PYTHON x 3 = ", linguagem * 3)
print("PYTHON x 2 = ", linguagem * 2)
print("PYTHON x 1 = ", linguagem * 1)
print()

